export const dummy = {
  dates: { maximum: '2023-02-13', minimum: '2022-12-27' },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/zjpYDQlhvrAaohKRShu522sKJ87.jpg',
      genre_ids: [16, 35, 18],
      id: 0,
      original_language: 'ja',
      release: '2023.01.04',
      genre: '애니메이션',
      language: '일본',
      limit: '12세이상관람가',
      running: '125분',
      original_title: 'THE FIRST SLAM DUNK',
      title: '더 퍼스트 슬램덩크',
      overview:
        "Shohoku's “speedster” and point guard, Ryota Miyagi, always plays with brains and lightning speed, running circles around his opponents while feigning composure. Born and raised in Okinawa, Ryota had a brother who was three years older. Following in the footsteps of his older brother, who was a famous local player from a young age, Ryota also became addicted to basketball. In his second year of high school, Ryota plays with the Shohoku High School basketball team along with Sakuragi, Rukawa, Akagi, and Mitsui as they take the stage at the Inter-High School National Championship. And now, they are on the brink of challenging the reigning champions, Sannoh Kogyo High School.",
      overviewKo: '제패를 꿈꾸는 북산고 농구부 5인방의 꿈과 열정, 멈추지 않는 도전을 그린 영화',
      popularity: 93.045,
      poster_path: '/rdPlVH2t6wmGYbe2Ii7P2pyi5hm.jpg',
      release_date: '2023-01-04',
      title: 'THE FIRST SLAM DUNK',
      video: false,
      vote_average: 8.3,
      vote_count: 12,
    },
    {
      adult: false,
      backdrop_path: '/tGwO4xcBjhXC0p5qlkw37TrH6S6.jpg',
      genre_ids: [16, 12, 35, 10751, 14],
      id: 1,
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      title: '장화 신은 고양이',
      release: '2023.01.04',
      genre: '애니메이션/어드벤쳐/코미디',
      language: '미국',
      limit: '12세이상관람가',
      running: '102분',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      overviewKo:
        '아홉 개의 목숨 중 단 하나의 목숨만 남은 장화신은 고양이 마지막 남은 목숨을 지키기 위해 히어로의 삶 대신 반려묘의 삶을 선택한 그에게 찾아온 마지막 기회, 바로 소원을 들어주는 소원별이 있는 곳을 알려주는 지도!',
      popularity: 2955.172,
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      release_date: '2023-01-04',
      title: 'Puss in Boots: The Last Wish',
      video: false,
      vote_average: 8.5,
      vote_count: 3656,
    },
    {
      adult: false,
      backdrop_path: '/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg',
      genre_ids: [878, 27, 35],
      id: 2,
      original_language: 'en',
      original_title: 'M3GAN',
      title: '메간',
      release: '2023.01.25',
      genre: '공포/스릴러/코미디',
      language: '미국',
      limit: '15세이상관람가',
      running: '102분',
      overview:
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      overviewKo:
        '너의 영원한 친구가 되어줄게. 교통사고로 부모를 잃고 혼자가 된 소녀 케이디. 로봇 엔지니어이자, 케이디의 보호자가 된 ‘젬마’는 ‘케이디’를 안전하게 지켜야 하는 프로그램이 입력된 AI 로봇 ‘메간’을 선물한다. 메간은 언제나 ‘케이디’의 곁을 지켜주며 함께 웃고, 힘들 땐 위로해주는 둘도 없는 친구가 된다. 어느 날, ‘케이디’가 위험에 처하자 메간은 예측할 수 없는 방향으로 업그레이드되며 감당할 수 없는 일들이 벌어지는데.. 우정에 OFF는 없어. 영원히',
      popularity: 1588.385,
      poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
      release_date: '2023-01-25',
      title: 'M3GAN',
      video: false,
      vote_average: 7.5,
      vote_count: 1558,
    },
    {
      adult: false,
      backdrop_path: '/vLPSvAt1CnfmDCeqG3zkFh0s6S4.jpg',
      genre_ids: [10752, 28],
      id: 3,
      original_language: 'en',
      original_title: 'Wolf Hound',
      title: '울프 하운드',
      release: '2023.01.09',
      genre: '액션/전쟁',
      language: '미국',
      limit: '15세이상관람가',
      running: '130분',
      overview:
        'Inspired by the real-life German special operations unit KG 200 that shot down, repaired, and flew Allied aircraft as Trojan horses, "Wolf Hound" takes place in 1944 German-occupied France and follows the daring exploits of Jewish-American fighter pilot Captain David Holden. Ambushed behind enemy lines, Holden must rescue a captured B-17 Flying Fortress crew, evade a ruthless enemy stalking him at every turn, and foil a plot that could completely alter the outcome of World War II.',
      overviewKo:
        '코드네임 ‘울프 하운드’ 런던 폭격을 막기 위한 비밀 전투 실화! 연합군의 전투비행단이 독일 전투기에 급습을 당한다. 홀로 적진에 추락한 파일럿은 독일군의 추격을 받고 런던 폭격의 일급 작전인 코드네임 ‘울프 하운드’를 알게 된다. 독일군 기지에 잠입해 포로로 잡힌 동료를 탈출시키고 폭격을 막기 위해 함께 지상전과 공중전을 벌이는데… 120분간의 논스톱 전쟁 액션을 만난다!',
      popularity: 781.12,
      poster_path: '/gHC0eFvXXNokP3sSNCTG2uks87R.jpg',
      release_date: '2023-02-09',
      title: 'Wolf Hound',
      video: false,
      vote_average: 6.8,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: '/rodjjIJ8oh9nuBp86PhojcYHTEN.jpg',
      genre_ids: [28, 9648, 53, 80],
      id: 4,
      original_language: 'en',
      original_title: 'Savage Salvation',
      title: '새비지 맨',
      release: '2023.01.26',
      genre: '액션/스릴러',
      language: '미국',
      limit: '청소년관람불가',
      running: '101분',
      overview:
        "Newly engaged Shelby John and Ruby Red want a fresh start after their struggles with addiction, but when Shelby discovers his beloved Ruby dead on their porch, he embarks on a vengeful killing spree of the dealers who supplied her. Armed with nothing but adrenaline and a nail gun, Shelby begins to unleash chaos on the town’s criminal underbelly, as he hunt’s down crime lord Coyote. Sheriff Church must race against the clock to put an end to Shelby's vigilante justice before the entire town descends into a bloodbath.",
      overviewKo:
        "마약 중독을 이겨내고 새로운 삶을 살길 원하는 ‘존’(잭 휴스턴)과 ‘루비’(윌라 피츠제럴드). 둘은 결혼을 약속하고 루비의 형부 ‘피터'(존 말코비치)는 존을 가족으로 따뜻하게 맞아준다. 과거의 죄를 씻고 구원을 바라는 루비의 세례를 앞둔 날, 약물 과다 투여로 죽어 있는 루비를 발견한 존은 절망에 빠지고 그녀를 죽음에 이르게 한 마약 공급책을 끝장내기 위해 복수에 나선다. 마을의 ‘마이크’ 보안관(로버트 드 니로)은 존의 폭주를 막기 위해 뒤를 쫓는데... 모든 것을 잃은 남자의 무자비한 끝장 복수가 시작된다!",
      popularity: 531.532,
      poster_path: '/fJRt3mmZEvf8gQzoNLzjPtWpc9o.jpg',
      release_date: '2023-01-26',
      title: 'Savage Salvation',
      video: false,
      vote_average: 6.6,
      vote_count: 101,
    },
    {
      adult: false,
      backdrop_path: '/vXjpwkXPirBmgdEpIknfN8ziDD.jpg',
      genre_ids: [16, 12, 14, 35],
      id: 5,
      original_language: 'ru',
      original_title: 'Мальчик-дельфин',
      title: '돌핀보이',
      release: '2023.01.25',
      genre: '어드밴처/애니메이션',
      language: '러시아, 이란, 터키',
      limit: '전체관람가',
      running: '85분',
      overview:
        'When a plane crashes at sea, dolphins rescue a little boy and raise him as family. He lives a carefree life beneath the waves until an evil monster seizes power over the underwater world. The boy is banished to dry land, where a kind-hearted captain takes him in. With the captain’s help, the boy sets out on a journey to solve the mystery of his true identity.',
      overviewKo:
        '돌고래야, 사람이야?! 정체를 알 수 없는 녀석이 온다! 바다 속 돌고래와 함께 자란 소년 ‘보이’ 어느 날 친엄마의 존재를 알게 된 ‘보이’는 자신의 뿌리를 궁금해하기 시작하고… 혼란스러운 상황 속 ‘보이’는 악당 ‘옥토퍼스’로 인해 엄마 돌고래 ‘나나’를 잃고 해안가로 떠밀려간다. 평생을 자신이 돌고래인 줄 알고 살던 ‘보이’는 해안가에 사는 ‘머버리드 선장’의 도움으로 친엄마를 찾아내기로 결심하는데... 2023년, 올겨울 유일무이 오션 어드벤처가 온다! ',
      popularity: 555.474,
      poster_path: '/gISoDEiaUH9BNEunmLC7FgUVaia.jpg',
      release_date: '2023-01-25',
      title: 'Dolphin Boy',
      video: false,
      vote_average: 5.7,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: '/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg',
      genre_ids: [18, 35],
      id: 6,
      original_language: 'en',
      original_title: 'Babylon',
      title: '바빌론',
      release: '2023.02.01',
      genre: '코미디/드라마',
      language: '미국',
      limit: '청소년관람불가',
      running: '189분',
      overview:
        "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
      overviewKo:
        '황홀하면서도 위태로운 고대 도시 ‘바빌론’에 비유되는 할리우드에서  전성기를 누리고 있는 당대 최고의 스타 ‘잭 콘래드’(브래드 피트).  누구나 ‘잭’과 같은 성공을 꿈꾸지만 아무나 이룰 수 없던 그 때,  화려한 데뷔를 위해 당차게 야망을 좇는 ‘넬리 라로이’(마고 로비)와  열정적인 청년 ‘매니 토레스’(디에고 칼바)가 영화 같은 삶을 꿈꾸며 할리우드에 입성한다. 하지만 할리우드에서는 기존 영화 산업의 틀을 깬 새로운 변화가 시작되고 그 격변의 한가운데에서 ‘잭’과 ‘넬리’, 그리고 ‘매니’는 살아남아 각자의 꿈을 이루기 위해 고군분투하는데... 모든 순간이 영화가 되는 곳. 뜨겁게 꿈꾸고, 거칠게 폭발한다!',
      popularity: 520.29,
      poster_path: '/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg',
      release_date: '2023-02-01',
      title: 'Babylon',
      video: false,
      vote_average: 7.7,
      vote_count: 1007,
    },
    {
      adult: false,
      backdrop_path: '/6YRQ8l93ZEs6x4rZojWoHIWdguK.jpg',
      genre_ids: [28, 80],
      id: 7,
      original_language: 'en',
      original_title: 'Detective Knight: Rogue',
      title: '디텍티브 나이트 : 가면의 밤',
      release: '2023.02.08',
      genre: '범죄/액션',
      language: '미국',
      limit: '15세이상관람가',
      running: '105분',
      overview:
        'As Los Angeles prepares for Halloween, mask-wearing armed robbers critically wound detective James Knight’s partner in a shootout following a heist. With Knight in hot pursuit, the bandits flee L.A. for New York, where the detective’s dark past collides with his present case and threatens to tear his world apart…unless redemption can claim Knight first.',
      overviewKo:
        '정의를 위해서라면 물불 가리지 않는 형사 나이트!  미국 전역에서 강도 사건이 발생하고 현장에 나간 동료 형사 ‘피츠제럴드’가 목숨을 잃는다. 전직 스포츠 선수들이 범인이라는 단서를 찾은 ‘나이트’는 그들의 배후에 불법 도박업자 ‘위나’가 있다는 사실을 알게 되고 복수와 정의를 위해 그들의 본거지인 뉴욕으로 향한 ‘나이트’ 과연 정의를 사수하고 복수를 실현할 수 있을까…',
      popularity: 318.953,
      poster_path: '/2wj5iUJ2B5AQ1lFctJgUrHHsp9B.jpg',
      release_date: '2023-02-09',
      title: 'Detective Knight: Rogue',
      video: false,
      vote_average: 6.7,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: '/59U5B10vsmVbgcCXzsFrzfG6SRb.jpg',
      genre_ids: [35, 10751, 10402],
      id: 8,
      original_language: 'en',
      original_title: 'Lyle, Lyle, Crocodile',
      title: '라일 라일 크로커다일',
      release: '2023.01.18',
      genre: '가족/뮤지컬/드라마',
      language: '미국',
      limit: '전체관람가',
      running: '105분',
      overview:
        'When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.',
      overviewKo:
        '뉴욕을 음악에 홀릴 마법이 펼쳐진다! 쇼맨 헥터(하비에르 바르뎀)는 어느 날 노래하는 악어 라일(숀 멘데스)을 발견하게 되고, 돈과 명예를 얻게 될 성공적인 무대를 꿈꾼다. 그러나 무대공포증에 있던 라일로 인해 무대는 실패하고 헥터는 라일을 홀로 도심에 남기고 떠난다. 한편, 뉴욕에 이사 온 프림 가족은 매일 밤 의문의 노랫소리로 신기한 경험을 하게 되고, 그 놀라운 정체와 마주하게 되면서 인생이 바뀌게 되는데…',
      popularity: 274.475,
      poster_path: '/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg',
      release_date: '2023-01-18',
      title: 'Lyle, Lyle, Crocodile',
      video: false,
      vote_average: 7.7,
      vote_count: 331,
    },
    {
      adult: false,
      backdrop_path: '/vmDa8HijINCAFYKqsMz0YM3sVyE.jpg',
      genre_ids: [28, 80, 53],
      id: 9,
      original_language: 'en',
      original_title: 'One Way',
      title: '원 웨이',
      release: '2023.02.09',
      genre: '액션',
      language: '미국',
      limit: '15세이상관람가',
      running: '97분',
      overview:
        'On the run with a bag full of cash after a robbing his former crime boss—and a potentially fatal wound—Freddy slips onto a bus headed into the unrelenting California desert. With his life slipping through his fingers, Freddy is left with very few choices to survive.',
      overviewKo:
        "죽여라! 도망쳐라! 살고 싶다면! 돌아갈 수 없는 편도행 버스 안에서 벌어지는 숨막히는 긴장감! 마약 조직의 보스 '빅'의 돈과 마약을 훔쳐 달아난 '프레디'는 야간 버스에 탑승해 도망친다. '빅'의 눈을 피해 도망갈 곳을 찾는 '프레디'는 친구인 '제이제이'와 아버지에게 전화를 걸며 도망칠 방법을 찾는다. 한편, 버스 안에는 집을 가출한 '레이첼'이 함께 탑승해 '프레디'에게 관심을 가지는데... 버스에서 내릴 수 없다면 목숨을 걸고 도망가야 한다. 과연, '프레디'는 무사히 버스에서 내려 가족을 만날 수 있을까?",
      popularity: 163.313,
      poster_path: '/uQCxOziq79P3wDsRwQhhkhQyDsJ.jpg',
      release_date: '2023-02-09',
      title: 'One Way',
      video: false,
      vote_average: 6.6,
      vote_count: 81,
    },
    {
      adult: false,
      backdrop_path: '/qAatLCuRhvLyNJbH5IGmxLyU3tx.jpg',
      genre_ids: [16, 14, 12],
      id: 10,
      original_language: 'ja',
      original_title: '劇場版 転生したらスライムだった件 紅蓮の絆編',
      title: '극장판 전생했더니 슬라임이었던 건에 대하여: 홍련의 인연편',
      release: '2023.02.02',
      genre: '애니메이션',
      language: '일본',
      limit: '15세이상관람가',
      running: '109분',
      overview:
        'A long-running conspiracy is swirling over a mysterious power wielded by the Queen in Raja, a small country west of Tempest. When a slime who evolved into a Demon Lord named Rimuru Tempest crosses paths with Hiiro, a survivor of the Ogre race, an incredible adventure packed with new characters begins. The power of bonds will be put to the test!',
      overviewKo:
        '[템페스트]의 서쪽에 위치한 [라자 소아국]. 한때는 금 채굴로 번영했지만 지금은 번영의 그림자는 찾아볼 수조차 없고,호수는 광산의 독에 오염되어 나라는 위기 상황에 처했다. 여왕 `토와`는 왕가에 대대로 전해 오는 왕관의 마력을 사용해 독을 제거하며 백성을 지키고 있었지만, 그 대가로 왕관에 걸려 있던 저주가 온몸에 퍼져 수명이 단축되고 있었다. 그러던 중, 템페스트에 갑자기 나타난 오거의 생존자 `히이로`. 베니마루 일행의 형님뻘이었다는 히이로는, 토와의 도움으로 살아남았던 것이었다. 자신을 구해 준 토와와 [라자 소아국]을 지키기 위해, 템페스트의 리무루에게 도움을 청하기 위해 온 히이로는 베니마루와 운명의 재회를 한다. 라자를 위기에서 구하기 위해, 그리고 토와에게 걸린 저주의 수수께끼를 풀기 위해, 리무루는 라자로 향하는데... 그곳에는 놀라운 음모가 기다리고 있었다!',
      popularity: 130.921,
      poster_path: '/pc75KETPdVnqHWCum3mFnmM0nSn.jpg',
      release_date: '2023-02-02',
      title: 'That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond',
      video: false,
      vote_average: 7.2,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: '/fjgKMNFo6uj7znrWwTbLzNBVzIT.jpg',
      genre_ids: [27, 9648],
      id: 11,
      original_language: 'en',
      original_title: 'The Twin',
      title: '',
      release: '',
      genre: '',
      language: '',
      limit: '',
      running: '',
      overview:
        "Every parent's worst nightmare is just the beginning for Rachel's ordeal as in the aftermath of a tragic accident, she and her husband Anthony decide to move to the other side of the world to focus on their surviving twin son Elliot.  What begins as a time of healing and isolation in the Finnish countryside turns into a desperate battle for the very soul of their son as an entity claiming to be his dead twin brother takes over Elliot — setting Rachel on a diabolical journey to unravel the horrible truth about her twin son.",
      popularity: 79.466,
      poster_path: '/uUUSkKQEptTHjYejxzaT5TVkiAG.jpg',
      release_date: '2023-02-08',
      title: 'The Twin',
      video: false,
      vote_average: 6,
      vote_count: 139,
    },
    {
      adult: false,
      backdrop_path: '/qp8qKiP7Q7zK4z3LItwWMHfV9kJ.jpg',
      genre_ids: [53],
      id: 12,
      original_language: 'en',
      original_title: 'The Desperate Hour',
      title: '트윈',
      release: '2023.02.08',
      genre: '공포',
      language: '핀란드',
      limit: '15세이상관람가',
      running: '108분',
      overview: 'A woman desperately races to save her child after police place her hometown on lockdown due to an active shooter incident.',
      overviewKo: '잉태된 공포, 이어지는 광기. 쌍둥이 아들을 잃은 레이첼 가족을 향해, 위로를 가장한 이교 집단의 손길이 뻗친다.',
      popularity: 65.436,
      poster_path: '/u6Pg9eTklhg6Aa7kXaxrfdE1Chi.jpg',
      release_date: '2023-01-04',
      title: 'The Desperate Hour',
      video: false,
      vote_average: 6.1,
      vote_count: 317,
    },
    {
      adult: false,
      backdrop_path: '/hhICjHximfBciqxX09d91GgghV8.jpg',
      genre_ids: [18],
      id: 13,
      original_language: 'en',
      original_title: 'Aftersun',
      title: '애프터썬',
      release: '2023.02.01',
      genre: '드라마',
      language: '영국, 미국',
      limit: '12세이상관람가',
      running: '101분',
      overview:
        "Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier. Memories real and imagined fill the gaps between miniDV footage as she tries to reconcile the father she knew with the man she didn't.",
      overviewKo: '아빠와 20여 년 전 갔던 튀르키예 여행. 둘만의 기억이 담긴 오래된 캠코더를 꺼내자 그해 여름이 물결처럼 출렁이기 시작한다.',
      popularity: 67.326,
      poster_path: '/hcGyKiQo6x9AL5GlssgBW3OAB4v.jpg',
      release_date: '2023-02-01',
      title: 'Aftersun',
      video: false,
      vote_average: 7.8,
      vote_count: 372,
    },
    {
      adult: false,
      backdrop_path: '/33qGtN2GpGEb94pn25PDPeWQZLk.jpg',
      genre_ids: [28],
      id: 14,
      original_language: 'en',
      original_title: 'Vendetta',
      title: '',
      release: '',
      genre: '',
      language: '',
      limit: '',
      running: '',
      overview:
        "When his daughter is murdered, William Duncan takes the law into his own hands, setting out on a quest for retribution. After killing the street thug responsible for her death, he finds himself in the middle of a war with the thug's brother, father, and their gang, who are equally hell-bent on getting even. What ensues is a tense back-and-forth game of vengeance. By the end, William comes to find that the quest for revenge never has a winner.",
      popularity: 53.992,
      poster_path: '/juah27ARLXRqbkgvlzilCs13s9S.jpg',
      release_date: '2023-01-20',
      title: 'Vendetta',
      video: false,
      vote_average: 6.3,
      vote_count: 199,
    },
    {
      adult: false,
      backdrop_path: '/9VIURlZvfnmFACs2m0MdUDDC3In.jpg',
      genre_ids: [14, 18, 10749],
      id: 15,
      original_language: 'en',
      original_title: 'Three Thousand Years of Longing',
      title: '벤데타: 복수의 시간 ',
      release: '2023.01.20',
      genre: '액션/스릴러',
      language: '미국',
      limit: '15세이상관람가',
      running: '96분',
      overview:
        'A solitary scholar discovers an ancient bottle while on a trip to Istanbul and unleashes a djinn who offers her three wishes. Filled with reluctance, she is unable to come up with one, so the djinn tries to inspire her with his stories.',
      overviewKo:
        "놈들을 향한 피의 응징이 시작된다! 딸과 함께 평온한 일상을 보내고 있던 '윌리엄 던컨'. 그러나 의문의 범죄 집단에 의해 딸이 잔혹하게 살해되는 사건이 발생하고, 그녀를 죽인 범인 '대니'는 가벼운 형만을 선고받게 된다. 결국 자신의 손으로 직접 딸의 복수를 결심한 '던컨'은 '대니'를 살해하지만, 이는 그가 속한 범죄 집단과의 전면전을 알리는 계기가 되어 끝도 없는 전쟁의 서막이 열리는데...",
      popularity: 32.621,
      poster_path: '/znTc7lqc7vrRLwAH7eRjbv6OQgS.jpg',
      release_date: '2023-01-04',
      title: 'Three Thousand Years of Longing',
      video: false,
      vote_average: 7.1,
      vote_count: 651,
    },
    {
      adult: false,
      backdrop_path: '/86X09HCJo8s83s32H2Frz7G0jMx.jpg',
      genre_ids: [99, 10402],
      id: 16,
      original_language: 'ko',
      original_title: '방탄소년단: 옛 투 컴 인 시네마',
      title: '방탄소년단: 옛 투 컴 인 시네마',
      release: '2023.02.01',
      genre: '공연',
      language: '한국',
      limit: '',
      running: '',
      overview:
        'Join RM, Jin, SUGA, j-hope, Jimin, V and Jung Kook in this special cinematic cut, re-edited and remixed for the big screen. Watch new close-up angles and a whole new view of the entire concert, BTS Yet To Come in Busan. Featuring hit songs from across the group\'s career, including "Dynamite," "Butter" and “IDOL," plus the first concert performance of "Run BTS" from the group’s latest album Proof.',
      overviewKo:
        'ARMY의 함성과 함께 전 세계 229개 국가/지역에서 즐긴 방탄소년단의 콘서트 ‘BTS Yet To Come in BUSAN’ 생중계에서는 만날 수 없었던 멤버들의 클로즈업뷰와 공연 전체를 3면 스크린으로 담아 다채로운 앵글을 그려내는 스크린X 히트곡 무대 릴레이와 최초 공개 퍼포먼스를 가장 완벽히 즐기는 4DX까지! 그날의 모든 순간을 초대형 스크린에서 다시 만난다',
      popularity: 21.244,
      poster_path: '/eWb45OsBHSO2t1j068bqDsPOGG9.jpg',
      release_date: '2023-02-01',
      title: 'BTS: Yet To Come in Cinemas',
      video: false,
      vote_average: 7.2,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: '/dp4jcu2tlAyJnJNnCyHXnWnqhUl.jpg',
      genre_ids: [80, 18, 53],
      id: 17,
      original_language: 'fa',
      original_title: 'عنکبوت مقدس',
      title: '',
      release: '',
      genre: '',
      language: '',
      limit: '',
      running: '',
      overview:
        'A journalist descends into the dark underbelly of the Iranian holy city of Mashhad as she investigates the serial killings of sex workers by the so called "Spider Killer", who believes he is cleansing the streets of sinners.',
      popularity: 22.572,
      poster_path: '/6ObJ4x7m1F5QRY06WzOxNJQHwGb.jpg',
      release_date: '2023-02-08',
      title: 'Holy Spider',
      video: false,
      vote_average: 7.3,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: '/skY1yDFcLF4h6CYDxndr5jHJNof.jpg',
      genre_ids: [28, 18],
      id: 18,
      original_language: 'cn',
      original_title: '天龍八部之喬峰傳',
      title: '',
      release: '',
      genre: '',
      language: '',
      limit: '',
      running: '',
      overview: "New adaptation of Louis Cha's wuxia novel Demi-Gods and Semi-Devils.",
      popularity: 16.902,
      poster_path: '/vksLBSmHahKD9F30vIrm0S7JsSO.jpg',
      release_date: '2023-01-25',
      title: 'Sakra',
      video: false,
      vote_average: 5.2,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: '/wPJKyDq1F9b4VtpF9dz8FPKVuS5.jpg',
      genre_ids: [9648, 10749, 878, 14],
      id: 19,
      original_language: 'zh',
      original_title: '想見你',
      title: '',
      release: '',
      genre: '',
      language: '',
      limit: '',
      running: '',
      overview: 'A film version of the Taiwanese hit drama "Someday or One Day," starring the original cast.',
      popularity: 31.165,
      poster_path: '/sbIa4aarctVOQvuIei2EAQi1TG0.jpg',
      release_date: '2023-01-25',
      title: 'Someday or One Day',
      video: false,
      vote_average: 5.7,
      vote_count: 7,
    },
  ],
  total_pages: 4,
  total_results: 70,
};
